✨ Admin panel
devs-nest/probable-adventure pull request #54
Opened 2021-09-20 17:09 UTC by samir-0711

2021-09-20 23:04 UTC, patheticGeek requested changes
Try doing the things i mentioned, if you need help ping me

2021-09-20 23:07 UTC, samir-0711 commented on src/utils/api.ts
> +  ADMIN_PANEL_ONBOARD: `api/v1/admin/users?filter[is_discord_form_filled]=true`,
You are reviewing outdated code.

2021-09-20 23:08 UTC, samir-0711 commented on src/services/admin.ts
> +  page_number: number
You are reviewing outdated code

2021-09-20 23:08 UTC, samir-0711 commented on src/services/admin.ts
> +  console.log(url)
You are reviewing outdated code

2021-09-20 23:08 UTC, samir-0711 commented on src/pages/Admin/Admin.tsx
> +    console.log(key)
You are reviewing outdated code

2021-09-23 17:04 UTC, sanjay270899 approved these changes

2021-09-24 09:29 UTC, patheticGeek approved these changes
LGTM

2021-09-24 12:20 UTC, merged